import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { getHeaderData } from "@/lib/getHeaderData";
import { getFooterData } from "@/lib/getFooterData";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({ subsets: ["latin"] });

const { menuItems } = await getHeaderData();
const headerData = await getHeaderData();
const footerData = await getFooterData();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased ${inter.className}`}
    >
      <body>
        <Header menuItems={headerData.menuItems} />
        {children}
        <Footer {...footerData} />
      </body>
    </html>
  );
}
